name: Check PR title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2.1.2
        with:
          require-multiple-commits: false
          auto-install: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
