name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-linters:
    name: Lint & Jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v16.6.1
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Run linters
        run: yarn lint
      - name: Test
        run: yarn test
  build: Build
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Build
        uses:  actions/setup-node@v2
        run: yarn run build
       
