name: build & lint & prettier
on:
  push:
    branches:    
      - master
jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - build: yarn run build
  lint:
    steps:
    runs-on: ubuntu-latest
      - lint: yarn run lint
