name: Lint & Prettier

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v16.6.1
      - name: Install dependencies
        run: yarn --prefer-offline
      # ESLint and Prettier must be in `package.json`
      - name: Run linters
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: Lint
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up node env
      uses: actions/setup-node@v2
      with:
        node-version: 'v16.6.1'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install yarn
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn run build
